#!/bin/sh
set -e

. /usr/share/debconf/confmodule

db_input high msttcorefonts/accepted-mscorefonts-eula || true
db_go || true

db_get msttcorefonts/accepted-mscorefonts-eula
if [ "$RET" != "true" ]; then
	echo "EULA not accepted" >&2
	exit 1
fi

exit 0
