#!/bin/sh
set -e

. /usr/share/debconf/confmodule

db_get msttcorefonts/accepted-mscorefonts-eula
if [ "$RET" != "true" ]; then
    echo "EULA not accepted, aborting installation." >&2
    exit 1
fi

#DEBHELPER#

exit 0
